server:
  port: 8083

spring:
#  application:
#    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fitness-recommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=
#    ${GEMINI_API_URL}
    key: AIzaSyCeEMOTesQ0bu2Brh4t7N3ZRkagKLQjWWc
#    ${GEMINI_API_KEY}